### ISSUE TITLE
[docker-build] How to use with docker-compose?

### ISSUE THREAD

**Issue by haf** [Dcard/yarn-plugins#24]
Since this is invoked via yarn, how do you make docker-compose use it?

**Comment by tommy351** [comment]
You have to build your Docker image with tags first.

```sh
yarn docker build your_workspace -t some_tag
```

Then use the built image in `docker-compose.yml`

```yaml
services:
  app:
    image: some_tag
```
